package com.mazid.models;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

// @Entity annotation indicates that this class represents a database entity.
@Entity
// Lombok annotations to automatically generate constructors, getters, setters, toString, hashCode, and equals methods.
@Data
@NoArgsConstructor // Generates a no-argument constructor
public class Chat {

    // @Id annotation marks the primary key of the entity.
    @Id
    // @GeneratedValue strategy indicates that the id field will be auto-generated by the database.
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    // The name of the chat, typically used to describe the chat room or group.
    private String chat_name;

    // The time when the chat was created or last active.
    private String chat_time;

    // @ManyToMany indicates a many-to-many relationship between users and chats.
    // Multiple users can participate in multiple chats.
    @ManyToMany
    private List<User> users = new ArrayList<>();

    // Timestamp indicating when the chat was created or last updated.
    private LocalDateTime timestamp;

    // @OneToMany indicates that one chat can have multiple messages.
    // Each message will be associated with a specific chat.
    @OneToMany(mappedBy = "chat")
    private List<Message> messages = new ArrayList<>();
}
