package com.mazid.models;

import jakarta.persistence.*;
import lombok.*;
// @Entity annotation indicates that this class represents a database entity.
@Entity
// Lombok annotations to generate constructors, getters, setters, toString, hashCode, and equals methods automatically.
@NoArgsConstructor // Generates a no-arguments constructor
@AllArgsConstructor // Generates a constructor with all fields
@Data // Generates getters, setters, toString, equals, and hashCode methods

public class Reels {

    @Id// @Id annotation marks the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.AUTO)// @GeneratedValue strategy indicates that the id field will be auto-generated by the database.
    private Integer id;

    private String title;// The title of the reel (short description).

    private String video;// Video file or URL associated with the reel.
    // @ManyToOne indicates that each reel is associated with one user.
    // Many reels can be associated with a single user.
    @ManyToOne
    private User user;


}
