package com.mazid.models;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;


@Entity// @Entity annotation indicates that this class represents a database entity.
@Data// Lombok's @Data annotation generates getters, setters, toString, equals, and hashCode methods automatically.
public class Story {

    @Id// @Id annotation marks the primary key of the entity.
    // @GeneratedValue strategy indicates that the id field will be auto-generated by the database.
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    // @ManyToOne indicates that each story is associated with a single user.
    // Multiple stories can belong to one user.
    @ManyToOne
    private User user;

    private String image;// The image associated with the story, which can be a URL or file path.

    private String captions;// Captions for the story, providing a description or text.

    private LocalDateTime timeStamp;// Timestamp indicating when the story was posted.
}
